module.exports = [
    {
        id: 1,
        lat: "-27.222633",
        lng: "-49.6455874",
        name: "Lar das Meninas",
        description: "Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.",
        images: ["https://source.unsplash.com/random?id=1","https://source.unsplash.com/random?id=2","https://source.unsplash.com/random?id=3"],
        instructions: "Venha como se sentir a vontade e traga muito amor e paciência pra dar.",
        opening_hours: "Horário de visitas das 18h at'e as 8h",
        open_on_weekends: "1",
    },
    {
        id: 2,
        lat: "-27.222633",
        lng: "-49.6555874",
        name: "Lar dos Meninos",
        description: "Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.",
        images: ["https://source.unsplash.com/random?id=1","https://source.unsplash.com/random?id=2","https://source.unsplash.com/random?id=3"],
        instructions: "Venha como se sentir a vontade e traga muito amor e paciência pra dar.",
        opening_hours: "Horário de visitas das 14h at'e as 8h",
        open_on_weekends: "1",
    },
    {
        id: 3,
        lat: "-27.232633",
        lng: "-49.6455874",
        name: "Lar des Menines",
        description: "Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.",
        images: ["https://source.unsplash.com/random?id=1","https://source.unsplash.com/random?id=2","https://source.unsplash.com/random?id=3"],
        instructions: "Venha como se sentir a vontade e traga muito amor e paciência pra dar.",
        opening_hours: "Horário de visitas das 17h at'e as 7h",
        open_on_weekends: "0",
    },
    {
        id: 4,
        lat: "-27.212633",
        lng: "-49.6355874",
        name: "Lar da ???",
        description: "Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.",
        images: ["https://source.unsplash.com/random?id=1","https://source.unsplash.com/random?id=2","https://source.unsplash.com/random?id=3"],
        instructions: "Venha como se sentir a vontade e traga muito amor e paciência pra dar.",
        opening_hours: "Horário de visitas das 19h at'e as 2h",
        open_on_weekends: "1",
    }
]